version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      RAILS_ENV: 'production'
      REDIS_URL: redis://redis:6379
    volumes:
      - public-data:/webapp/public
      - log-data:/webapp/log
      - tmp-data:/webapp/tmp
    depends_on:
      - redis
    command: bundle exec puma -C config/puma.rb
  worker:
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      RAILS_ENV: 'production'
      REDIS_URL: redis://redis:6379
    volumes:
      - public-data:/webapp/public
      - log-data:/webapp/log
      - tmp-data:/webapp/tmp
    depends_on:
      - redis
    command: bundle exec sidekiq
  redis:
    image: redis
    volumes:
      - redis:/data
  nginx:
    build:
      context: containers/nginx
    ports:
      - 80:80
    volumes:
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
    depends_on:
      - web
volumes:
  public-data:
  log-data:
  tmp-data:
  redis: