version: '3'
services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile.prod
    environment:
      REDIS_URL: redis://redis:6379
      RAILS_ENV: 'production'
    volumes:
      - bundle:/bundle
      - tmp-data:/webapp/tmp
      - public-data:/webapp/public
    depends_on:
      - redis
  web:
    <<: *app
    command: bundle exec puma -C config/puma.rb
  worker:
    <<: *app
    command: bundle exec sidekiq --environment=production
  redis:
    image: redis
  nginx:
    build:
      context: containers/nginx
    ports:
      - 80:80
    depends_on:
      - web
volumes:
  public-data:
  log-data:
  tmp-data:
  bundle: