version: '3'
services:
  app: &app
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        RUBY_VERSION: '2.6.3'
        NODE_MAJOR: '11'
        YARN_VERSION: '1.13.0'
        BUNDLER_VERSION: '2.0.2'
    environment:
      REDIS_URL: redis://redis:6379
      RAILS_ENV: 'production'
    volumes:
      - .:/webapp:cached
      - bundle:/bundle
      - tmp-data:/webapp/tmp
      - public-data:/webapp/public
    depends_on:
      - redis
  web:
    <<: *app
    command: bundle exec puma -C config/puma.rb
  worker:
    <<: *app
    command: bundle exec sidekiq
  redis:
    image: redis
    volumes:
      - redis:/data
  nginx:
    build:
      context: containers/nginx
    ports:
      - 80:80
    volumes:
      - public-data:/webapp/public
      - tmp-data:/webapp/tmp
    depends_on:
      - web
volumes:
  public-data:
  log-data:
  tmp-data:
  redis:
  bundle: