version: '3'
services:
  app: &app
    build:
      context: .
      args:
        RUBY_VERSION: '2.6.3'
        NODE_MAJOR: '11'
        YARN_VERSION: '1.13.0'
        BUNDLER_VERSION: '2.0.2'
    environment:
      REDIS_URL: redis://redis:6379
    volumes:
      - .:/webapp:cached
      - rails_cache:/webapp/tmp/cache
      - bundle:/bundle
    depends_on:
      - db
      - redis
  web:
    <<: *app
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
    - "3000:3000"
    tty: true
    stdin_open: true
  worker:
    <<: *app
    command: bundle exec sidekiq
  redis:
    image: redis
    volumes:
      - redis:/data
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data:
  bundle:
  rails_cache:
  redis: